In [1]:
import pandas as pd
import json
import torch

In [2]:
partPath = 'TwiBot-22-com/'
dirPath = 'TwiBot-22/'

In [3]:
dfTweet = pd.read_csv(partPath + 'tweetMinCols.csv')

In [4]:
dfTweet

id                   uid  uidMap  countDays
0       t1499693636107190272           u2443666806    1813         11
1       t1499087527193583627           u3067857869    3388         13
2       t1497700449411076100           u1375007264    6080         17
3       t1495439610297843713  u1397042382701400068    1673         23
4       t1128656436291153921            u117514645    6173       1035
...                      ...                   ...     ...        ...
984712  t1496590935957901315            u311932430     655         20
984713  t1495138932740268032  u1057363273832636417    2570         24
984714  t1499765247971840004            u143608676    3678         11
984715  t1492482983172919296   u725629991271186432    7253         31
984716  t1491043883241062404            u373907847     189         35

[984717 rows x 4 columns]

In [5]:
dfUser = pd.read_json(partPath + 'user.json')
dfUser

created_at                                        description  \
0    2016-09-02 17:13:51                ‏‏‏Abdelwahed Wajih\nعبدالواحد وجيه   
1    2009-10-29 08:21:28        Try my best in all my way to life happily..   
2    2018-06-06 19:11:31                                waiting......2022⭐⭐   
3    2014-05-25 14:02:22                            #Bugdroidy #FCIS #Barca   
4    2021-03-25 15:48:41                      رب الخير لا ياتى إلا بالخير 🖤   
...                  ...                                                ...   
8689 2020-05-04 19:20:34  egyptian illustrator, comic artist, and magica...   
8690 2020-05-18 02:15:44                     irgendwie irgendwo irgendwann.   
8691 2011-10-26 19:01:06                  ‏‏الراعي الرسمي لتايم لاين الانمي   
8692 2008-05-20 16:07:04  Founder and CEO, 👕🚀\nSports and Gaming\n\nForm...   
8693 2009-03-25 12:57:54  Marvel comics writer: X-FACTOR, GWENPOOL STRIK...   

                                               entities                    id  \
0     {'url': {'urls': [{'start': 0, 'end': 23, 'url...   u771758047412748288   
1                                                  None             u86020763   
2     {'url': {'urls': [{'start': 0, 'end': 23, 'url...  u1004440668763230210   
3     {'url': {'urls': [{'start': 0, 'end': 23, 'url...           u2522772534   
4                                                  None  u1375112149157216258   
...                                                 ...                   ...   
8689  {'url': {'urls': [{'start': 0, 'end': 23, 'url...  u1257389639318585345   
8690                                               None  u1262205160983605250   
8691                                               None            u398927679   
8692  {'url': {'urls': [{'start': 0, 'end': 23, 'url...             u14846901   
8693  {'url': {'urls': [{'start': 0, 'end': 23, 'url...             u26490474   

                  location                              name  pinned_tweet_id  \
0                     None                   عبد الواحد وجيه              NaN   
1                Indonesia                       bernardinus              NaN   
2       El Qaliobia, Egypt                          Alhassan              NaN   
3             Cairo, Egypt                     khaled sherif              NaN   
4                     None                  Nada Abd Alrhman              NaN   
...                    ...                               ...              ...   
8689          20 | she/her         ✨Nour T✨ COMMISSIONS OPEN     1.428708e+18   
8690                  None                            Dwight              NaN   
8691            Laugh Tale  الكايزوكو اوني والناكاما بتوعه 🤓     1.231680e+18   
8692            Dallas, TX   Chris Chaney marcaurel.eth 🇩🇪🇺🇸              NaN   
8693  the boneyard, krakoa                     Leah Williams              NaN   

                                      profile_image_url  protected  \
0     https://pbs.twimg.com/profile_images/771764768...      False   
1     https://pbs.twimg.com/profile_images/349683458...      False   
2     https://pbs.twimg.com/profile_images/145774969...      False   
3     https://pbs.twimg.com/profile_images/123885339...      False   
4     https://pbs.twimg.com/profile_images/145660076...      False   
...                                                 ...        ...   
8689  https://pbs.twimg.com/profile_images/147849174...      False   
8690  https://pbs.twimg.com/profile_images/136715285...      False   
8691  https://pbs.twimg.com/profile_images/148066499...      False   
8692  https://pbs.twimg.com/profile_images/126828321...      False   
8693  https://pbs.twimg.com/profile_images/882723937...      False   

                                         public_metrics  \
0     {'followers_count': 2461, 'following_count': 2...   
1     {'followers_count': 93, 'following_count': 98,...   
2     {'followers_count': 61, 'following_count': 139...   
3     {'followers_count': 287, 'following_

In [6]:
userList = dfUser['id'].tolist()

In [7]:
userMap = {userList[i] : i for i in range(len(userList))}

In [8]:
userMap['u26490474']

8693

In [9]:
tidList = dfTweet['id'].tolist()
tidMap = {tidList[i]: i for i in range(len(tidList))}

In [10]:
tidMap['t1499765247971840004']

984714

In [11]:
dfTweet['tidMap'] = dfTweet['id'].map(tidMap)
dfTweet['uidMap'] = dfTweet['uid'].map(userMap)
dfTweet

id                   uid  uidMap  countDays  tidMap
0       t1499693636107190272           u2443666806    1813         11       0
1       t1499087527193583627           u3067857869    3388         13       1
2       t1497700449411076100           u1375007264    6080         17       2
3       t1495439610297843713  u1397042382701400068    1673         23       3
4       t1128656436291153921            u117514645    6173       1035       4
...                      ...                   ...     ...        ...     ...
984712  t1496590935957901315            u311932430     655         20  984712
984713  t1495138932740268032  u1057363273832636417    2570         24  984713
984714  t1499765247971840004            u143608676    3678         11  984714
984715  t1492482983172919296   u725629991271186432    7253         31  984715
984716  t1491043883241062404            u373907847     189         35  984716

[984717 rows x 5 columns]

In [12]:
catFeatures = torch.load(partPath + 'tweet_cat_properties.pt')
numFeatures = torch.load(partPath + 'tweet_num_properties.pt')

In [13]:
dfTweetSet = dfTweet.groupby('uid', as_index=False).agg(list)
dfTweetSet

uid                                                 id  \
0     u1000214682530074624  [t1487251470932389890, t1487252858601115654, t...   
1     u1001476869454270464  [t1502840669722890240, t1502663597134077955, t...   
2               u100182925  [t1491352634766561280, t1489548283056123906, t...   
3               u100195084                             [t1260878148691845123]   
4     u1002058355974852608  [t1495890029561978886, t1495886245343473669, t...   
...                    ...                                                ...   
8134             u99881380  [t1123461391644549121, t1059701095851798528, t...   
8135   u999180747557634048  [t1358659806421131264, t1367010613923176448, t...   
8136   u999192247206862855  [t1074091484469780481, t1059465755404759040, t...   
8137   u999256776213229570  [t1497817587081781248, t1494807056603308036, t...   
8138            u999616946  [t1499454658661789696, t1499356545188089856, t...   

                                                 uidMap  \
0     [1081, 1081, 1081, 1081, 1081, 1081, 1081, 108...   
1     [4879, 4879, 4879, 4879, 4879, 4879, 4879, 487...   
2     [1598, 1598, 1598, 1598, 1598, 1598, 1598, 159...   
3                                                [6136]   
4     [5194, 5194, 5194, 5194, 5194, 5194, 5194, 519...   
...                                                 ...   
8134  [5286, 5286, 5286, 5286, 5286, 5286, 5286, 528...   
8135  [2374, 2374, 2374, 2374, 2374, 2374, 2374, 237...   
8136  [6003, 6003, 6003, 6003, 6003, 6003, 6003, 600...   
8137  [3830, 3830, 3830, 3830, 3830, 3830, 3830, 383...   
8138  [5876, 5876, 5876, 5876, 5876, 5876, 5876, 587...   

                                              countDays  \
0     [45, 45, 45, 45, 45, 87, 87, 45, 45, 38, 45, 4...   
1     [2, 3, 27, 32, 20, 28, 20, 23, 20, 12, 28, 27,...   
2     [34, 39, 33, 35, 37, 36, 34, 34, 39, 38, 39, 3...   
3                                                 [670]   
4     [22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 2...   
...                                                 ...   
8134  [1049, 1225, 1240, 1194, 42, 129, 134, 37, 118...   
8135  [400, 377, 378, 427, 445, 362, 353, 417, 45, 4...   
8136  [1186, 1226, 1228, 1161, 1208, 1210, 1223, 118...   
8137  [16, 25, 18, 14, 18, 19, 14, 14, 27, 9, 18, 13...   
8138  [12, 12, 12, 13, 12, 11, 12, 11, 13, 11, 13, 1...   

                                                 tidMap  
0     [517113, 519716, 519756, 520466, 521028, 52109...  
1     [38497, 51642, 701280, 710571, 716942, 717290,...  
2     [516397, 516476, 516747, 516779, 517956, 51824...  
3                                              [823559]  
4     [812927, 816053, 817048, 818525, 821206, 82201...  
...                                                 ...  
8134  [80605, 80728, 80757, 80937, 81438, 83246, 840...  
8135  [717743, 726325, 729113, 729385, 731731, 73588...  
8136  [375592, 375673, 376057, 377598, 377826, 37941...  
8137  [83137, 84379, 86687, 89975, 96160, 97707, 987...  
8138  [752, 1693, 2879, 3585, 3846, 4397, 5042, 9660...  

[8139 rows x 5 columns]

In [14]:
dfTweetSet['uidMap'] = dfTweetSet['uidMap'].apply(lambda x:x[0])
dfTweetSet

uid                                                 id  \
0     u1000214682530074624  [t1487251470932389890, t1487252858601115654, t...   
1     u1001476869454270464  [t1502840669722890240, t1502663597134077955, t...   
2               u100182925  [t1491352634766561280, t1489548283056123906, t...   
3               u100195084                             [t1260878148691845123]   
4     u1002058355974852608  [t1495890029561978886, t1495886245343473669, t...   
...                    ...                                                ...   
8134             u99881380  [t1123461391644549121, t1059701095851798528, t...   
8135   u999180747557634048  [t1358659806421131264, t1367010613923176448, t...   
8136   u999192247206862855  [t1074091484469780481, t1059465755404759040, t...   
8137   u999256776213229570  [t1497817587081781248, t1494807056603308036, t...   
8138            u999616946  [t1499454658661789696, t1499356545188089856, t...   

      uidMap                                          countDays  \
0       1081  [45, 45, 45, 45, 45, 87, 87, 45, 45, 38, 45, 4...   
1       4879  [2, 3, 27, 32, 20, 28, 20, 23, 20, 12, 28, 27,...   
2       1598  [34, 39, 33, 35, 37, 36, 34, 34, 39, 38, 39, 3...   
3       6136                                              [670]   
4       5194  [22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 2...   
...      ...                                                ...   
8134    5286  [1049, 1225, 1240, 1194, 42, 129, 134, 37, 118...   
8135    2374  [400, 377, 378, 427, 445, 362, 353, 417, 45, 4...   
8136    6003  [1186, 1226, 1228, 1161, 1208, 1210, 1223, 118...   
8137    3830  [16, 25, 18, 14, 18, 19, 14, 14, 27, 9, 18, 13...   
8138    5876  [12, 12, 12, 13, 12, 11, 12, 11, 13, 11, 13, 1...   

                                                 tidMap  
0     [517113, 519716, 519756, 520466, 521028, 52109...  
1     [38497, 51642, 701280, 710571, 716942, 717290,...  
2     [516397, 516476, 516747, 516779, 517956, 51824...  
3                                              [823559]  
4     [812927, 816053, 817048, 818525, 821206, 82201...  
...                                                 ...  
8134  [80605, 80728, 80757, 80937, 81438, 83246, 840...  
8135  [717743, 726325, 729113, 729385, 731731, 73588...  
8136  [375592, 375673, 376057, 377598, 377826, 37941...  
8137  [83137, 84379, 86687, 89975, 96160, 97707, 987...  
8138  [752, 1693, 2879, 3585, 3846, 4397, 5042, 9660...  

[8139 rows x 5 columns]

In [15]:
dfTweetSet = dfTweetSet.sort_values(by=['uidMap'])

In [16]:
dfTweetSet['dayMin'] = dfTweetSet['countDays'].apply(min)
dfTweetSet['dayMax'] = dfTweetSet['countDays'].apply(max)
dfTweetSet['dayRange'] = dfTweetSet['dayMax'] - dfTweetSet['dayMin']
rangeList = dfTweetSet['dayRange'].tolist()

In [17]:
edgeList1dayOri = [[], []]
edgeList10dayOri = [[], []]
edgeList20dayOri = [[], []]
edgeList50dayOri = [[], []]
num1day = []
cat1day = []
num10day = []
cat10day = []
num20day = []
cat20day = []
num50day = []
cat50day = []

In [18]:
rangeList[:10]

[2008, 1526, 46, 1863, 0, 0, 828, 950, 643, 1757]

In [19]:
dayLenList = [days + 1 for days in rangeList]

In [20]:
numFeatures.shape

torch.Size([984717, 12])

In [21]:
catFeatures.shape

torch.Size([984717, 14])

In [22]:
torch.tensor([[0, 0, 0], [0, 0, 0]]).shape

torch.Size([2, 3])

In [23]:
l0 = [0] * 3
l0[0] += 1
l0

[1, 0, 0]

In [24]:
import math
math.ceil(11/10)

2

In [25]:
math.ceil(10/10)

1

## 向上取整
得到的结果应该是/inter之后的向上取整的数值，如果数值不对之后可能会很奇怪，最好不要有空白之类的

In [26]:
NUM_NUM = numFeatures.shape[1]
CAT_NUM = catFeatures.shape[1]

In [27]:
[[0, 0, 0]] * 2

[[0, 0, 0], [0, 0, 0]]

In [28]:
num0 = [0] * 4
num1 = [num0, num0]

In [29]:
num1[0][0] += 1
num1

[[1, 0, 0, 0], [1, 0, 0, 0]]

In [30]:
edgeList1dayOri = [[], []]
edgeList10dayOri = [[], []]
edgeList20dayOri = [[], []]
edgeList50dayOri = [[], []]
num1day = []
cat1day = []
num10day = []
cat10day = []
num20day = []
cat20day = []
num50day = []
cat50day = []
start1day, start10day, start20day, start50day = 0, 0, 0, 0
for day in dayLenList:
    # feature matrix initialize
    num1day += [[0] * NUM_NUM] * day
    cat1day += [[0] * CAT_NUM] * day
    day10 = math.ceil(day / 10)
    day20 = math.ceil(day / 20)
    day50 = math.ceil(day / 50)
    num10day += [[0] * NUM_NUM] * day10
    cat10day += [[0] * CAT_NUM] * day10
    num20day += [[0] * NUM_NUM] * day20
    cat20day += [[0] * CAT_NUM] * day20
    num50day += [[0] * NUM_NUM] * day50
    cat50day += [[0] * CAT_NUM] * day50
    # get original edge information
    edgeList1dayOri[0] += list(range(start1day, start1day + day - 1))
    edgeList1dayOri[1] += list(range(start1day + 1, start1day + day))
    edgeList10dayOri[0] += list(range(start10day, start10day + day10 - 1))
    edgeList10dayOri[1] += list(range(start10day + 1, start10day + day10))
    edgeList20dayOri[0] += list(range(start20day, start20day + day20 - 1))
    edgeList20dayOri[1] += list(range(start20day + 1, start20day + day20))
    edgeList50dayOri[0] += list(range(start50day, start50day + day50 - 1))
    edgeList50dayOri[1] += list(range(start50day + 1, start50day + day50))
    # update start day information
    start1day += day
    start10day += day10
    start20day += day20
    start50day += day50

In [31]:
len(num1day)

4837817

In [32]:
len(edgeList1dayOri[0])

4829678

In [33]:
len(edgeList10dayOri[0])

479404

In [34]:
len(edgeList20dayOri[0])

237721

In [35]:
len(edgeList50dayOri[0])

92810

In [36]:
len(num1day[0])

12

In [127]:
def getTensor(t0):
    return torch.tensor(t0, dtype=torch.float32)
num1day = getTensor(num1day)
num1day

/var/folders/pk/9j79n0j97l96355kp67lwjxr0000gn/T/ipykernel_41033/3677302870.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(t0, dtype=torch.float32)


tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [128]:
num1day.shape

torch.Size([4837817, 12])

In [129]:
cat1day = getTensor(cat1day)
num10day = getTensor(num10day)
cat10day = getTensor(cat10day)
num20day = getTensor(num20day)
cat20day = getTensor(cat20day)
num50day = getTensor(num50day)
cat50day = getTensor(cat50day)

/var/folders/pk/9j79n0j97l96355kp67lwjxr0000gn/T/ipykernel_41033/3677302870.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(t0, dtype=torch.float32)


In [106]:
torch.save(num1day, partPath + 'num1day.pt')
torch.save(cat1day, partPath + 'cat1day.pt')
torch.save(num10day, partPath + 'num10day.pt')
torch.save(cat10day, partPath + 'cat10day.pt')
torch.save(num20day, partPath + 'num20day.pt')
torch.save(cat20day, partPath + 'cat20day.pt')
torch.save(num50day, partPath + 'num50day.pt')
torch.save(cat50day, partPath + 'cat50day.pt')

## remain task: aggregate data & add reply and other edge info
### aggregate data

In [107]:
dfTweetSet

uid                                                 id  \
7147   u771758047412748288  [t968552557307195393, t1484691801902620676, t1...   
7553             u86020763  [t6296873895, t27437350015, t32218780471095705...   
21    u1004440668763230210  [t1024212295092789248, t1023258628327923712, t...   
4276           u2522772534  [t897975690850598917, t815620028905177089, t92...   
2450  u1375112149157216258                             [t1462435130291728393]   
...                    ...                                                ...   
7532   u855444364771942400                             [t1445094680518172691]   
1385  u1257389639318585345  [t1502764262204321793, t1495819872428826631, t...   
1428  u1262205160983605250  [t1494755763897745419, t1494274109643145222, t...   
5714            u398927679  [t1495849266589351939, t1495847359326179334, t...   
4447             u26490474  [t1487517811211739136, t1484027823807508485, t...   

      uidMap                                          countDays  \
7147       0  [1477, 52, 328, 1035, 334, 330, 2020, 72, 222,...   
7553       1  [4485, 4169, 3260, 3408, 4515, 3038, 3806, 432...   
21         2   [1323, 1326, 1323, 1325, 1337, 1369, 1337, 1323]   
4276       3  [1671, 1899, 1609, 1385, 1901, 1900, 1876, 188...   
2450       4                                              [114]   
...      ...                                                ...   
7532    8688                                              [162]   
1385    8689  [3, 22, 24, 27, 22, 32, 29, 32, 23, 24, 22, 27...   
1428    8690  [25, 26, 20, 23, 32, 25, 35, 24, 23, 29, 44, 3...   
5714    8691  [22, 22, 22, 22, 22, 22, 22, 22, 20, 22, 22, 2...   
4447    8693  [45, 54, 29, 69, 69, 60, 60, 60, 60, 69, 70, 6...   

                                                 tidMap  dayMin  dayMax  \
7147  [82013, 84348, 84801, 86893, 89539, 89675, 904...      12    2020   
7553  [80302, 80569, 82268, 82359, 82550, 82597, 828...    2994    4520   
21    [81841, 85277, 93473, 105209, 116850, 117892, ...    1323    1369   
4276  [79988, 80062, 80112, 80193, 80491, 80637, 807...      48    1911   
2450                                           [207564]     114     114   
...                                                 ...     ...     ...   
7532                                           [415509]     162     162   
1385  [75837, 520757, 521325, 521513, 522219, 523197...       3     207   
1428  [811338, 814784, 815484, 816126, 817017, 81859...      20      44   
5714  [2212, 2732, 3609, 3788, 4867, 7626, 7973, 939...       6     751   
4447  [719284, 719448, 727447, 728056, 728177, 73559...       1    1581   

      dayRange                                         count10day  \
7147      2008  [147, 5, 32, 103, 33, 33, 202, 7, 22, 31, 3, 1...   
7553      1526  [448, 416, 326, 340, 451, 303, 380, 432, 383, ...   
21          46           [132, 132, 132, 132, 133, 136, 133, 132]   
4276      1863  [167, 189, 160, 138, 190, 190, 187, 188, 162, ...   
2450         0                                               [11]   
...        ...                                                ...   
7532         0                                               [16]   
1385       204  [0, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 2, 2, 1, 3, ...   
1428        24  [2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 4, 3, 3, 2, 4, ...   
5714       745  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...   
4447      1580  [4, 5, 2, 6, 6, 6, 6, 6, 6, 6, 7, 6, 2, 6, 2, ...   

                                             count20day  \
7147  [73, 2, 16, 51, 16, 16, 101, 3, 11, 15, 1, 6, ...   
7553  [224, 208, 163, 170, 225, 151, 190, 216, 191, ...   
21                     [66, 66, 66, 66, 66, 68, 66, 66]   
4276  [83, 94, 80, 69, 95, 95, 93, 94, 81, 93, 59, 6...   
2450                                                [5]   
...                                                 ...   
7532                                                [8]   
1385  [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [108]:
def getInters(dayList, inters):
    return list([day // inters for day in dayList])
getInters([1, 10, 11], 10)

[0, 1, 1]

In [109]:
dfTweetSet['count10day'] = dfTweetSet['countDays'].apply(lambda x: getInters(x, 10))
dfTweetSet['count20day'] = dfTweetSet['countDays'].apply(lambda x: getInters(x, 20))
dfTweetSet['count50day'] = dfTweetSet['countDays'].apply(lambda x: getInters(x, 50))

In [110]:
dfTweetSet

uid                                                 id  \
7147   u771758047412748288  [t968552557307195393, t1484691801902620676, t1...   
7553             u86020763  [t6296873895, t27437350015, t32218780471095705...   
21    u1004440668763230210  [t1024212295092789248, t1023258628327923712, t...   
4276           u2522772534  [t897975690850598917, t815620028905177089, t92...   
2450  u1375112149157216258                             [t1462435130291728393]   
...                    ...                                                ...   
7532   u855444364771942400                             [t1445094680518172691]   
1385  u1257389639318585345  [t1502764262204321793, t1495819872428826631, t...   
1428  u1262205160983605250  [t1494755763897745419, t1494274109643145222, t...   
5714            u398927679  [t1495849266589351939, t1495847359326179334, t...   
4447             u26490474  [t1487517811211739136, t1484027823807508485, t...   

      uidMap                                          countDays  \
7147       0  [1477, 52, 328, 1035, 334, 330, 2020, 72, 222,...   
7553       1  [4485, 4169, 3260, 3408, 4515, 3038, 3806, 432...   
21         2   [1323, 1326, 1323, 1325, 1337, 1369, 1337, 1323]   
4276       3  [1671, 1899, 1609, 1385, 1901, 1900, 1876, 188...   
2450       4                                              [114]   
...      ...                                                ...   
7532    8688                                              [162]   
1385    8689  [3, 22, 24, 27, 22, 32, 29, 32, 23, 24, 22, 27...   
1428    8690  [25, 26, 20, 23, 32, 25, 35, 24, 23, 29, 44, 3...   
5714    8691  [22, 22, 22, 22, 22, 22, 22, 22, 20, 22, 22, 2...   
4447    8693  [45, 54, 29, 69, 69, 60, 60, 60, 60, 69, 70, 6...   

                                                 tidMap  dayMin  dayMax  \
7147  [82013, 84348, 84801, 86893, 89539, 89675, 904...      12    2020   
7553  [80302, 80569, 82268, 82359, 82550, 82597, 828...    2994    4520   
21    [81841, 85277, 93473, 105209, 116850, 117892, ...    1323    1369   
4276  [79988, 80062, 80112, 80193, 80491, 80637, 807...      48    1911   
2450                                           [207564]     114     114   
...                                                 ...     ...     ...   
7532                                           [415509]     162     162   
1385  [75837, 520757, 521325, 521513, 522219, 523197...       3     207   
1428  [811338, 814784, 815484, 816126, 817017, 81859...      20      44   
5714  [2212, 2732, 3609, 3788, 4867, 7626, 7973, 939...       6     751   
4447  [719284, 719448, 727447, 728056, 728177, 73559...       1    1581   

      dayRange                                         count10day  \
7147      2008  [147, 5, 32, 103, 33, 33, 202, 7, 22, 31, 3, 1...   
7553      1526  [448, 416, 326, 340, 451, 303, 380, 432, 383, ...   
21          46           [132, 132, 132, 132, 133, 136, 133, 132]   
4276      1863  [167, 189, 160, 138, 190, 190, 187, 188, 162, ...   
2450         0                                               [11]   
...        ...                                                ...   
7532         0                                               [16]   
1385       204  [0, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 2, 2, 1, 3, ...   
1428        24  [2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 4, 3, 3, 2, 4, ...   
5714       745  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...   
4447      1580  [4, 5, 2, 6, 6, 6, 6, 6, 6, 6, 7, 6, 2, 6, 2, ...   

                                             count20day  \
7147  [73, 2, 16, 51, 16, 16, 101, 3, 11, 15, 1, 6, ...   
7553  [224, 208, 163, 170, 225, 151, 190, 216, 191, ...   
21                     [66, 66, 66, 66, 66, 68, 66, 66]   
4276  [83, 94, 80, 69, 95, 95, 93, 94, 81, 93, 59, 6...   
2450                                                [5]   
...                                                 ...   
7532                                                [8]   
1385  [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [111]:
num10day.shape

torch.Size([487543, 12])

In [112]:
count1day = dfTweetSet['countDays'].tolist()
count10day = dfTweetSet['count10day'].tolist()
count20day = dfTweetSet['count20day'].tolist()
count50day = dfTweetSet['count50day'].tolist()

In [113]:
tid1day = {}
tid10day = {}
tid20day = {}
tid50day = {}

In [114]:
tidMapList = dfTweetSet['tidMap'].tolist()

In [115]:
def gettidmap(idList, dayList):
    dayMap = {}
    for i in range(len(idList)):
        tid0 = idList[i]
        day0 = dayList[i]
        if day0 not in dayMap.keys():
            dayMap[day0] = [tid0]
        else:
            dayMap[day0].append(tid0)
    return dayMap

gettidmap([10, 20, 30], [1, 1, 3])

{1: [10, 20], 3: [30]}

In [116]:
map1dayList = [gettidmap(tidMapList[i], count1day[i]) for i in range(len(tidMapList))]
map1dayList[0]

{1477: [82013],
 52: [84348, 128462],
 328: [84801],
 1035: [86893],
 334: [89539],
 330: [89675, 99733, 106665],
 2020: [90492, 166957],
 72: [92017, 182219],
 222: [92519, 192561],
 318: [94279, 98388, 192233],
 37: [95697],
 138: [97614, 194764, 225148],
 45: [101036],
 333: [101704, 115200],
 63: [103107, 103295],
 1668: [103590],
 327: [104700, 110432, 120321],
 948: [105658],
 315: [112437, 198301, 229839],
 244: [119502],
 547: [120776],
 378: [123303],
 313: [124711, 211694],
 270: [130446],
 1595: [130809],
 50: [132478],
 283: [132748],
 284: [136712, 198775, 218261],
 444: [138257],
 1188: [140512],
 1720: [142882],
 1285: [143252],
 310: [146498, 154032, 167138, 174961, 176349, 182320],
 112: [147919, 195110],
 1591: [150063],
 280: [152766],
 232: [156230],
 1522: [156584],
 76: [158597],
 137: [159984],
 42: [165916, 195214, 227051],
 262: [166865],
 329: [172110],
 233: [173838],
 324: [176535, 187032],
 1852: [176891, 186768],
 292: [181609],
 319: [190262, 194678],
 18

In [117]:
a = torch.rand((3, 4))
a

tensor([[0.4459, 0.2632, 0.1680, 0.8846],
        [0.4001, 0.1476, 0.9897, 0.2228],
        [0.9142, 0.7298, 0.8217, 0.7162]])

In [118]:
b = torch.ones(4)
b

tensor([1., 1., 1., 1.])

In [119]:
a[0] += b
a

tensor([[1.4459, 1.2632, 1.1680, 1.8846],
        [0.4001, 0.1476, 0.9897, 0.2228],
        [0.9142, 0.7298, 0.8217, 0.7162]])

In [120]:
map10dayList = [gettidmap(tidMapList[i], count10day[i]) for i in range(len(tidMapList))]
map20dayList = [gettidmap(tidMapList[i], count20day[i]) for i in range(len(tidMapList))]
map50dayList = [gettidmap(tidMapList[i], count50day[i]) for i in range(len(tidMapList))]

In [121]:
dayMinList = dfTweetSet['dayMin'].tolist()
dayMinList[:10]

[12, 2994, 1323, 48, 114, 1064, 42, 11, 10, 2]

In [122]:
def getFeatures(idList):
    num = len(idList)
    num0 = torch.zeros(NUM_NUM, dtype=torch.float32)
    cat0 = torch.zeros(CAT_NUM, dtype=torch.float32)
    for tid in idList:
        num0 += numFeatures[tid]
        cat0 += catFeatures[tid]
    num0 /= num
    cat0 /= num
    return num0, cat0

getFeatures([89675, 99733, 106665])

(tensor([1.0000e+00, 6.6667e-01, 5.3333e+00, 3.3333e-01, 0.0000e+00, 0.0000e+00,
         6.6667e-01, 0.0000e+00, 5.1000e+01, 7.3533e+02, 1.1667e+01, 4.2000e+01]),
 tensor([0.3333, 0.0000, 1.0000, 1.0000, 0.0000, 0.6667, 0.0000, 0.6667, 1.0000,
         1.0000, 0.0000, 1.0000, 0.0000, 0.0000]))

In [123]:
numFeatures[89675], numFeatures[99733], numFeatures[106665]

(tensor([  3,   2,  13,   1,   0,   0,   2,   0,  94, 676,  11,  42]),
 tensor([  0,   0,   2,   0,   0,   0,   0,   0,  32, 113,   1,  42]),
 tensor([   0,    0,    1,    0,    0,    0,    0,    0,   27, 1417,   23,   42]))

In [124]:
catFeatures[89675], catFeatures[99733], catFeatures[106665]

(tensor([1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0]),
 tensor([0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0]),
 tensor([0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0]))

In [125]:
dayLenList[0]

2009

In [131]:
dayMinList[0]

12

In [133]:
min1days = [min(days) for days in count1day]
min10days = [min(days) for days in count10day]
min20days = [min(days) for days in count20day]
min50days = [min(days) for days in count50day]

In [134]:
start1day = 0
start10day = 0
start20day = 0
start50day = 0
from tqdm import trange
for i in trange(len(tidMapList)):
    min1day, min10day, min20day, min50day = min1days[i], min10days[i], min20days[i], min50days[i]
    map1day = map1dayList[i]
    for day in map1day.keys():
        num0, cat0 = getFeatures(map1day[day])
        day0 = day - min1day
        num1day[start1day + day0] += num0
        cat1day[start1day + day0] += cat0
    map10day = map10dayList[i]
    for day in map10day.keys():
        num0, cat0 = getFeatures(map10day[day])
        day0 = day - min10day
        num10day[start10day + day0] += num0
        cat10day[start10day + day0] += cat0
    map20day = map20dayList[i]
    for day in map20day.keys():
        num0, cat0 = getFeatures(map20day[day])
        day0 = day - min20day
        num20day[start20day + day0] += num0
        cat20day[start20day + day0] += cat0
    map50day = map50dayList[i]
    for day in map50day.keys():
        num0, cat0 = getFeatures(map50day[day])
        day0 = day - min50day
        num50day[start50day + day0] += num0
        cat50day[start50day + day0] += cat0
    # update index info
    day0 = dayLenList[i]
    day10 = math.ceil(day0 / 10)
    day20 = math.ceil(day0 / 20)
    day50 = math.ceil(day0 / 50)
    start1day += day0
    start10day += day10
    start20day += day20
    start50day += day50

100%|█████████████████████████████████████████████████████████████████████████████████| 8139/8139 [00:36<00:00, 222.21it/s]


In [135]:
num1day[0]

tensor([4.0000e+00, 0.0000e+00, 9.5000e+00, 0.0000e+00, 0.0000e+00, 5.0000e-01,
        0.0000e+00, 5.0000e-01, 7.2500e+01, 7.6300e+02, 1.2000e+01, 4.2000e+01])

In [136]:
num1day[1]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [137]:
torch.save(num1day, partPath + 'num1day.pt')
torch.save(cat1day, partPath + 'cat1day.pt')
torch.save(num10day, partPath + 'num10day.pt')
torch.save(cat10day, partPath + 'cat10day.pt')
torch.save(num20day, partPath + 'num20day.pt')
torch.save(cat20day, partPath + 'cat20day.pt')
torch.save(num50day, partPath + 'num50day.pt')
torch.save(cat50day, partPath + 'cat50day.pt')

## add full edges
1. build tid-node index map
2. add edge info

In [138]:
tidNodeMap1 = {}
tidNodeMap10 = {}
tidNodeMap20 = {}
tidNodeMap50 = {}

In [141]:
start1day = 0
start10day = 0
start20day = 0
start50day = 0
for i in trange(len(dayLenList)):
    min1day, min10day, min20day, min50day = min1days[i], min10days[i], min20days[i], min50days[i]
    tids = tidMapList[i]
    days1 = count1day[i]
    days10 = count10day[i]
    days20 = count20day[i]
    days50 = count50day[i]
    for j in range(len(tids)):
        tid0 = tids[j]
        day1 = days1[j]
        day10 = days10[j]
        day20 = days20[j]
        day50 = days50[j]
        tidNodeMap1[tid0] = start1day + day1 - min1day
        tidNodeMap10[tid0] = start10day + day10 - min10day
        tidNodeMap20[tid0] = start20day + day20 - min20day
        tidNodeMap50[tid0] = start50day + day50 - min50day
    # update index info
    day0 = dayLenList[i]
    day10 = math.ceil(day0 / 10)
    day20 = math.ceil(day0 / 20)
    day50 = math.ceil(day0 / 50)
    start1day += day0
    start10day += day10
    start20day += day20
    start50day += day50

100%|███████████████████████████████████████████████████████████████████████████████| 8139/8139 [00:00<00:00, 11128.58it/s]


In [142]:
len(tidNodeMap1.keys())

984717

In [143]:
tidNodeMap1[686138]

0

In [145]:
tidNodeMap1[713873]

18

In [147]:
len(tidNodeMap10.keys())

984717

In [148]:
dfEdge = pd.read_csv(partPath + 'edge.csv')
dfEdge

source_id    relation             target_id
0        u1012124895088726016   following           u1599552121
1                  u152731757   following             u30026226
2                  u799145528   following           u2397208592
3                  u902120672   following            u225189569
4                  u799145528   following  u1108640256474132480
...                       ...         ...                   ...
1027306  t1263338516915859457   retweeted  t1263228699484262400
1027307  t1464800121028292611   retweeted  t1464795723900276740
1027308  t1421439998654615553   retweeted  t1421438967887585283
1027309   t506421397824880640   retweeted   t506388938915729408
1027310  t1488516374548856835  replied_to  t1488469083460976642

[1027311 rows x 3 columns]

In [149]:
relaList = dfEdge['relation'].tolist()
for rela in set(relaList):
    print(rela, relaList.count(rela))

followers 3855
following 13504
quoted 1485
post 984717
replied_to 12209
retweeted 11541


In [151]:
relaTweets = ['retweeted', 'quoted', 'replied_to']
dfTweetEdge = dfEdge.loc[dfEdge['relation'].isin(relaTweets)]
dfTweetEdge

source_id    relation             target_id
1002076  t1268274950907015168  replied_to  t1268161763138297858
1002077  t1427342075205341191   retweeted  t1427341204509835264
1002078  t1412726752959512577  replied_to  t1412726751961223168
1002079  t1483511703258435584  replied_to  t1483505495168143370
1002080  t1491361887996768258  replied_to  t1491361116219650048
...                       ...         ...                   ...
1027306  t1263338516915859457   retweeted  t1263228699484262400
1027307  t1464800121028292611   retweeted  t1464795723900276740
1027308  t1421439998654615553   retweeted  t1421438967887585283
1027309   t506421397824880640   retweeted   t506388938915729408
1027310  t1488516374548856835  replied_to  t1488469083460976642

[25235 rows x 3 columns]

In [152]:
len(tidMap.keys())

984717

In [153]:
dfTweetEdge['sid'] = dfTweetEdge['source_id'].map(tidMap)
dfTweetEdge['tid'] = dfTweetEdge['target_id'].map(tidMap)
dfTweetEdge

/var/folders/pk/9j79n0j97l96355kp67lwjxr0000gn/T/ipykernel_41033/3185184780.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTweetEdge['sid'] = dfTweetEdge['source_id'].map(tidMap)
/var/folders/pk/9j79n0j97l96355kp67lwjxr0000gn/T/ipykernel_41033/3185184780.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTweetEdge['tid'] = dfTweetEdge['target_id'].map(tidMap)


source_id    relation             target_id     sid  \
1002076  t1268274950907015168  replied_to  t1268161763138297858  178780   
1002077  t1427342075205341191   retweeted  t1427341204509835264  106296   
1002078  t1412726752959512577  replied_to  t1412726751961223168  182330   
1002079  t1483511703258435584  replied_to  t1483505495168143370  203232   
1002080  t1491361887996768258  replied_to  t1491361116219650048  104574   
...                       ...         ...                   ...     ...   
1027306  t1263338516915859457   retweeted  t1263228699484262400  181233   
1027307  t1464800121028292611   retweeted  t1464795723900276740  224917   
1027308  t1421439998654615553   retweeted  t1421438967887585283  102125   
1027309   t506421397824880640   retweeted   t506388938915729408  200283   
1027310  t1488516374548856835  replied_to  t1488469083460976642  144140   

            tid  
1002076  939704  
1002077  976176  
1002078  174386  
1002079  971126  
1002080  978009  
...         ...  
1027306  921858  
1027307  922897  
1027308  917216  
1027309  972569  
1027310  980810  

[25235 rows x 5 columns]

In [154]:
replysidList = dfTweetEdge.loc[dfTweetEdge['relation'] == 'replied_to']['sid'].tolist()
replytidList = dfTweetEdge.loc[dfTweetEdge['relation'] == 'replied_to']['tid'].tolist()

In [155]:
quotesidList = dfTweetEdge.loc[dfTweetEdge['relation'] == 'quoted']['sid'].tolist()
quotetidList = dfTweetEdge.loc[dfTweetEdge['relation'] == 'quoted']['tid'].tolist()

In [156]:
retweetsidList = dfTweetEdge.loc[dfTweetEdge['relation'] == 'retweeted']['sid'].tolist()
retweettidList = dfTweetEdge.loc[dfTweetEdge['relation'] == 'retweeted']['tid'].tolist()

In [159]:
def getEdge(inters):
    if inters == 1:
        map0 = tidNodeMap1
    elif inters == 10:
        map0 = tidNodeMap10
    elif inters == 20:
        map0 = tidNodeMap20
    else:
        map0 = tidNodeMap50
    edgeReply = [[], []]
    edgeRetweet = [[], []]
    edgeQuote = [[], []]
    replynode1 = [map0[id0] for id0 in replysidList]
    replynode2 = [map0[id0] for id0 in replytidList]
    retweetnode1 = [map0[id0] for id0 in retweetsidList]
    retweetnode2 = [map0[id0] for id0 in retweettidList]
    quotenode1 = [map0[id0] for id0 in quotesidList]
    quotenode2 = [map0[id0] for id0 in quotetidList]
    edgeReply = [list(replynode1), list(replynode2)]
    edgeRetweet = [list(retweetnode1), list(retweetnode2)]
    edgeQuote = [list(quotenode1), list(quotenode2)]
    reply = torch.tensor(edgeReply, dtype=int)
    torch.save(reply, partPath + 'edgeList' + str(inters) + 'DayReply.pt')
    quote = torch.tensor(edgeQuote, dtype=int)
    torch.save(quote, partPath + 'edgeList' + str(inters) + 'DayQuote.pt')
    retweet = torch.tensor(edgeRetweet, dtype=int)
    torch.save(retweet, partPath + 'edgeList' + str(inters) + 'DayRetweet.pt')
    return


In [160]:
getEdge(1)

In [161]:
getEdge(10)

In [162]:
getEdge(20)

In [163]:
getEdge(50)

In [37]:
edgeList1dayOri = torch.tensor(edgeList1dayOri, dtype=int)
torch.save(edgeList1dayOri, partPath + 'edgeList1DayOrigin.pt')

In [38]:
edgeList10dayOri = torch.tensor(edgeList10dayOri, dtype=int)
torch.save(edgeList10dayOri, partPath + 'edgeList10DayOrigin.pt')

In [39]:
edgeList20dayOri = torch.tensor(edgeList20dayOri, dtype=int)
torch.save(edgeList20dayOri, partPath + 'edgeList20DayOrigin.pt')

In [40]:
edgeList50dayOri = torch.tensor(edgeList50dayOri, dtype=int)
torch.save(edgeList50dayOri, partPath + 'edgeList50DayOrigin.pt')

In [168]:
with open(partPath + 'userTweetNums1Day.json', 'w') as f:
    f.write(json.dumps(dayLenList))

In [170]:
with open(partPath + 'userTweetNums10Day.json', 'w') as f:
    dayLenList10 = list([math.ceil(day / 10) for day in dayLenList])
    f.write(json.dumps(dayLenList10))

In [171]:
with open(partPath + 'userTweetNums20Day.json', 'w') as f:
    dayLenList20 = list([math.ceil(day / 20) for day in dayLenList])
    f.write(json.dumps(dayLenList20))

In [172]:
with open(partPath + 'userTweetNums50Day.json', 'w') as f:
    dayLenList50 = list([math.ceil(day / 50) for day in dayLenList])
    f.write(json.dumps(dayLenList50))

In [187]:
def getDayRange(dayLenList):
    start = 0
    dayRange = []
    for day in dayLenList:
        dayRange.append(start)
        start += day
    dayRange.append(start)
    return dayRange

getDayRange([10, 2, 3, 9])

[0, 10, 12, 15, 24]

In [174]:
dayLenList[:10]

[2009, 1527, 47, 1864, 1, 1, 829, 951, 644, 1758]

In [188]:
with open(partPath + 'userTweetNums1Day.json', 'w') as f:
    f.write(json.dumps(getDayRange(dayLenList)))

In [189]:
with open(partPath + 'userTweetNums10Day.json', 'w') as f:
    dayLenList10 = list([math.ceil(day / 10) for day in dayLenList])
    f.write(json.dumps(getDayRange(dayLenList10)))

In [190]:
with open(partPath + 'userTweetNums20Day.json', 'w') as f:
    dayLenList20 = list([math.ceil(day / 20) for day in dayLenList])
    f.write(json.dumps(getDayRange(dayLenList20)))

In [191]:
with open(partPath + 'userTweetNums50Day.json', 'w') as f:
    dayLenList50 = list([math.ceil(day / 50) for day in dayLenList])
    f.write(json.dumps(getDayRange(dayLenList50)))

In [180]:
getDayRange(dayLenList20[:10])

[0, 101, 178, 181, 275, 276, 277, 319, 367, 400]

In [181]:
num20day[:10]

tensor([[5.3333e+00, 0.0000e+00, 2.0667e+01, 0.0000e+00, 0.0000e+00, 6.6667e-01,
         0.0000e+00, 1.3333e+00, 1.3667e+02, 1.4420e+03, 2.2667e+01, 8.4000e+01],
        [2.0000e+01, 0.0000e+00, 1.1333e+01, 0.0000e+00, 0.0000e+00, 1.3333e+00,
         6.6667e-01, 0.0000e+00, 2.0867e+02, 1.1480e+03, 1.8000e+01, 8.4000e+01],
        [4.5714e+00, 1.7143e+00, 2.6000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         1.1429e+00, 0.0000e+00, 1.1857e+02, 1.1591e+03, 1.8571e+01, 8.4000e+01],
        [1.2500e+01, 4.2500e+00, 6.6250e+01, 5.0000e-01, 0.0000e+00, 0.0000e+00,
         1.0000e+00, 0.0000e+00, 1.0650e+02, 8.8400e+02, 1.4000e+01, 8.4000e+01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0000e+00, 2.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 1.0500e+02, 1.6300e+02, 2.0000e+00, 8.4000e+01],
        [7.0000e+00, 3

In [183]:
num20day.shape

torch.Size([245860, 12])

In [185]:
dayRange20 = getDayRange(dayLenList20)
dayRange20[-1]

245780

In [186]:
dayLenList[-1]

1581

In [192]:
len(dayRange20)

8139

In [ ]:
uidMap1 = dfTweetSet['uidMap'].tolist()

In [195]:
uidMap2 = dfUser['id'].tolist()
len(uidMap2), uidMap2[:10]

(8694,
 ['u771758047412748288',
  'u86020763',
  'u1004440668763230210',
  'u2522772534',
  'u1375112149157216258',
  'u1118067018035449856',
  'u1184578525455622150',
  'u145169990',
  'u148390293',
  'u17659206'])

In [197]:
len(uidMap1)

8139

In [199]:
uidMap1[:100]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 81,
 82,
 83,
 84,
 85,
 86,
 88,
 89,
 90,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 104,
 105,
 106,
 107]

In [200]:
m0 = [[1]* 4, [2] * 4, [3] * 4, [4] * 4]
m0 = torch.tensor(m0, dtype=int)
m0

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])

In [212]:
index0 = torch.tensor([2, 1, 0, 3], dtype=int)
index0

tensor([2, 1, 0, 3])

In [214]:
m0[index0]

tensor([[3, 3, 3, 3],
        [2, 2, 2, 2],
        [1, 1, 1, 1],
        [4, 4, 4, 4]])

In [215]:
len(uidMap1)

8139

In [216]:
len(uidMap2)

8694

In [217]:
reIndex = uidMap1
for i in range(len(uidMap2)):
    if i not in uidMap1:
        reIndex.append(i)

In [218]:
len(reIndex)

8694

In [219]:
reIndex[-100:-1]

[7322,
 7435,
 7461,
 7475,
 7478,
 7479,
 7483,
 7487,
 7490,
 7493,
 7494,
 7550,
 7551,
 7557,
 7558,
 7562,
 7567,
 7573,
 7580,
 7598,
 7606,
 7611,
 7647,
 7733,
 7800,
 7818,
 7824,
 7862,
 7891,
 7904,
 7906,
 7909,
 7916,
 7921,
 7940,
 7947,
 7950,
 7954,
 7956,
 7962,
 7963,
 7974,
 7985,
 7989,
 7991,
 7992,
 7993,
 7994,
 7995,
 8000,
 8004,
 8014,
 8015,
 8018,
 8019,
 8021,
 8022,
 8039,
 8054,
 8056,
 8103,
 8109,
 8119,
 8129,
 8148,
 8165,
 8166,
 8179,
 8188,
 8189,
 8191,
 8219,
 8237,
 8238,
 8245,
 8248,
 8257,
 8260,
 8261,
 8262,
 8270,
 8271,
 8273,
 8299,
 8343,
 8360,
 8376,
 8387,
 8389,
 8400,
 8405,
 8415,
 8464,
 8488,
 8504,
 8508,
 8538,
 8610,
 8669]

In [220]:
reIndex[8000:8139]

[8552,
 8553,
 8554,
 8555,
 8556,
 8557,
 8558,
 8559,
 8560,
 8561,
 8562,
 8563,
 8564,
 8565,
 8566,
 8567,
 8568,
 8569,
 8570,
 8571,
 8572,
 8573,
 8574,
 8575,
 8576,
 8577,
 8578,
 8579,
 8580,
 8581,
 8582,
 8583,
 8584,
 8585,
 8586,
 8587,
 8588,
 8589,
 8590,
 8591,
 8592,
 8593,
 8594,
 8595,
 8596,
 8597,
 8598,
 8599,
 8600,
 8601,
 8602,
 8603,
 8604,
 8605,
 8606,
 8607,
 8608,
 8609,
 8611,
 8612,
 8613,
 8614,
 8615,
 8616,
 8617,
 8618,
 8619,
 8620,
 8621,
 8622,
 8623,
 8624,
 8625,
 8626,
 8627,
 8628,
 8629,
 8630,
 8631,
 8632,
 8633,
 8634,
 8635,
 8636,
 8637,
 8638,
 8639,
 8640,
 8641,
 8642,
 8643,
 8644,
 8645,
 8646,
 8647,
 8648,
 8649,
 8650,
 8651,
 8652,
 8653,
 8654,
 8655,
 8656,
 8657,
 8658,
 8659,
 8660,
 8661,
 8662,
 8663,
 8664,
 8665,
 8666,
 8667,
 8668,
 8670,
 8671,
 8672,
 8673,
 8674,
 8675,
 8676,
 8677,
 8678,
 8679,
 8680,
 8681,
 8682,
 8683,
 8684,
 8685,
 8686,
 8687,
 8688,
 8689,
 8690,
 8691,
 8693]

In [221]:
reIndex[8139:8200]

[11,
 19,
 43,
 53,
 80,
 87,
 91,
 103,
 108,
 117,
 125,
 129,
 132,
 145,
 148,
 155,
 167,
 168,
 170,
 177,
 185,
 191,
 234,
 238,
 239,
 270,
 276,
 284,
 292,
 297,
 300,
 302,
 310,
 312,
 318,
 329,
 346,
 347,
 348,
 388,
 390,
 401,
 402,
 405,
 406,
 407,
 408,
 409,
 414,
 421,
 432,
 445,
 452,
 458,
 476,
 709,
 710,
 723,
 820,
 1017,
 1029]

In [222]:
reIndex = torch.tensor(reIndex, dtype=int)
torch.save(reIndex, partPath + 're_index.pt')